### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by ritika1159** [IGRSoft/IGRPhotoTweaks#10]
Hi,

I have seen that but i want to know that when user select the image for
first time it is setting cropview as of imagesize. It is calculating
maxbounds (). I want to know how will it set 1:1 aspect ratio and lock it
by default.

Thanks
 Ritika

**Comment by iKorich** [comment]
Hi @ritika1159 

self.setCropAspectRect(aspect: "1:1")
self.lockAspectRatio(true)
