### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by khushDesai** [IGRSoft/IGRPhotoTweaks#14]
I am trying to run this code  and i have installed pods but i got error like in following image, Please Help.
![screen shot 2017-10-05 at 11 21 58 am](https://user-images.githubusercontent.com/29880773/31212688-880d6eae-a9bf-11e7-9a7b-c3f6239bd7cd.png)

**Comment by iKorich** [comment]
@khushDesai thank you for feedback
I'll check in few day, releasing app now...

**Comment by kalvish21** [comment]
Getting the same exact error here.
