### ISSUE TITLE
Crash while cropping panorama image

### ISSUE THREAD

**Issue by GaneshManickam** [IGRSoft/IGRPhotoTweaks#16]
App getting crashed while cropping panorama image

**Comment by porzal** [comment]
+1

**Comment by denismars** [comment]
Same here - seems this library is becoming stale. Hope we can fix.

**Comment by GaneshManickam** [comment]
I'm using below code to avoid crash but still this library not support panorama image crop. Use below code to avoid crash

```
  func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]){
        print("didFinishPickingMediaWithInfo")
        if let pickedImage = info[UIImagePickerControllerOriginalImage] as? UIImage {
            picker.dismiss(animated: false, completion: { () -> Void in
                
                let smallest = min(pickedImage.size.width, pickedImage.size.height)
                let largest = max(pickedImage.size.width, pickedImage.size.height)
                let ratio = largest/smallest
                if (ratio >= CGFloat(2/1)) || (ratio >= CGFloat(4/1)) || (ratio >= CGFloat(10/1)) {
                    // it is probably a panorama
                    print( "Panorama can't set for profile image")
                } else {
                    //Pass image to cropper here
                }
            })
        }
    }
```

**Comment by ykying** [comment]
Because library using the original image width as the output image width.
E.x: 100000x500 -> 1:1 crop -> 100000x100000 (memory issue crash)
Simple fix:
**CGImage+IGRPhonoTweakExtension.swift**
New param: zoomScale
func transformedImage(_ transform: CGAffineTransform, zoomScale: CGFloat, sourceSize: CGSize, cropSize: CGSize, imageViewSize: CGSize) -> CGImage {
        let expectedWidth = floor(sourceSize.width / imageViewSize.width * cropSize.width) / zoomScale
        let expectedHeight = floor(sourceSize.height / imageViewSize.height * cropSize.height) / zoomScale

        let outputSize = CGSize(width: expectedWidth, height: expectedHeight)
        let bitmapBytesPerRow = 0


**IGRPhotoTweakViewController.swift** Line 126, replace the function call
            let imageRef = fixedImage.transformedImage(transform,
                                                       zoomScale: self.photoView.scrollView.zoomScale,
                                                       sourceSize: self.image.size,
                                                       cropSize: self.photoView.cropView.frame.size,
                                                       imageViewSize: self.photoView.photoContentView.bounds.size)

**Comment by iKorich** [comment]
@ykying Thank You!

Merged fix
