### ISSUE TITLE
IGRPhotoTweakViewController+AspectRatio swift file missing 

### ISSUE THREAD

**Issue by nirajjoshi** [IGRSoft/IGRPhotoTweaks#17]
IGRPhotoTweakViewController+AspectRatio swift file missing when install through pods in version 1.0.6.
Thus not able to use **"lockAspectRatio"** method.

**Comment by Sub-Zero-1** [comment]
Same here

**Comment by nirajjoshi** [comment]
Any Updates on the Reported issue?

**Comment by iKorich** [comment]
Fixed in v1.0.7
