### ISSUE TITLE
After setting the aspect ratio, user should not be able to change it. 

### ISSUE THREAD

**Issue by mihirpmehta** [IGRSoft/IGRPhotoTweaks#2]
If I am setting the aspect ratio to 16:9 , because i want to force user to maintain that aspect ration while selecting the image. 

User is able to change the aspect ratio to something else other than 9:16 

There should be Boolean variable for example shouldLockAspectRatio , If that variable is set to be true , User should not be able to change the aspect ratio.

**Comment by mihirpmehta** [comment]
I have changed the code and created pull request for the same.

**Comment by iKorich** [comment]
hi @mihirpmehta, please see example,
That was text mistake

**Comment by iKorich** [comment]
Your Pull request was broke master!
Pull request has been removed

**Comment by iKorich** [comment]
You should make pull to get latest source and correct apply your changes
