### ISSUE TITLE
photoView.scrollView.contentOffset 

### ISSUE THREAD

**Issue by MohammadrezaZamanieh** [IGRSoft/IGRPhotoTweaks#27]
i have cropRect with photoView.scrollView.contentOffset but in ipad and plus devices it returns wrong point

**Comment by iKorich** [comment]
@MohammadrezaZamanieh thank you for feedback, I'll try check it in few weeks, have a lot of work

**Comment by iKorich** [comment]
@MohammadrezaZamanieh I have correct rect on iPhone 8+ and all simulators, 
please provide more info.
