### ISSUE TITLE
Latest update does not reflact via Pods for swift 4.2 support

### ISSUE THREAD

**Issue by linustech** [IGRSoft/IGRPhotoTweaks#38]
I have added IGRPhotoTweaks to my project using cocoapods which downloading version '1.0.7'. But it does not contains updated code with Swift 4.2 support. I have attached screenshots here:

Screenshot 1:
![screen shot 2019-01-02 at 2 57 01 pm](https://user-images.githubusercontent.com/3788607/50586477-9aba4b80-0e9f-11e9-98b8-3c8db109be8f.png)

Screenshot 2:
![screen shot 2019-01-02 at 3 01 15 pm](https://user-images.githubusercontent.com/3788607/50586487-a9a0fe00-0e9f-11e9-94a1-9f0d38fccf0b.png)

Screenshot 3:
![screen shot 2019-01-02 at 3 00 25 pm](https://user-images.githubusercontent.com/3788607/50586492-adcd1b80-0e9f-11e9-9508-1611e9700159.png)

Screenshot 4:
![screen shot 2019-01-02 at 3 00 46 pm](https://user-images.githubusercontent.com/3788607/50586497-b291cf80-0e9f-11e9-8f67-caa5f2d7e339.png)

Screenshot 5:
![screen shot 2019-01-02 at 3 01 08 pm](https://user-images.githubusercontent.com/3788607/50586499-b58cc000-0e9f-11e9-9654-7a77f0fa2d24.png)

**Comment by iKorich** [comment]
added in 731e377874ee546d4fd7e93bd61988d0e882e792
will be in v1.0.8
