### ISSUE TITLE
how to rotate 90°

### ISSUE THREAD

**Issue by iOSleep** [IGRSoft/IGRPhotoTweaks#4]
when i set slider to -90~90 the crop area do not match the image.
wish your help.

**Comment by iKorich** [comment]
Hi @iOSleep , thats very easy:

fileprivate func setupSlider() {
    self.angleSlider?.minimumValue = -Float(IGRRadianAngle.toRadians(90))
    self.angleSlider?.maximumValue = Float(IGRRadianAngle.toRadians(90))
    self.angleSlider?.value = 0.0
}

@IBAction func onChandeAngleSliderValue(_ sender: UISlider) {
    let radians: CGFloat = CGFloat(sender.value)
    self.changedAngle(value: radians)
}

please see example

**Comment by iOSleep** [comment]
...when you rotate to 90/-90, cropMaskView can't change the size.
