### ISSUE TITLE
Should zoom to screen after scale changes

### ISSUE THREAD

**Issue by shoaibhussan15** [IGRSoft/IGRPhotoTweaks#45]
Whenever user dragged to crop
it should zoop to fill screen same in photos app
or user change aspect ratio value from action sheet should also zoom to screen
how to implement this functionality.

**Comment by iKorich** [comment]
zoom works like in photos app

**Comment by shoaibhussan15** [comment]
but aspect ration doesn't work well for landscape images like if we select image with 1920*1080 and apply 9:16 on it.it will show cropped area less than half of screen.

**Comment by iKorich** [comment]
working on correct rects now...
