### ISSUE TITLE
pods file missing

### ISSUE THREAD

**Issue by ritika1159** [IGRSoft/IGRPhotoTweaks#7]
Hi

Pods file are missing in the project

<img width="252" alt="screen shot 2017-05-23 at 7 03 45 pm" src="https://cloud.githubusercontent.com/assets/28085396/26356756/b12969bc-3fea-11e7-8805-6d142016d3f7.png">

I created new pod file and new work space for example. After this pods issue got resolved, but after this horizontalDial was not available.

Anyone can help me out its little urgent !!

Thanks

**Comment by iKorich** [comment]
🤦‍♂️
`cd Example
pod install`
